name: Build

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Linux-specific dependencies
      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          # Make libarchive-c optional - installation may fail on some platforms
          pip install libarchive-c || echo "libarchive-c installation skipped - some archive formats may not be supported"



      # Build with PyInstaller
      - name: Build with PyInstaller (Linux)
        if: runner.os == 'Linux'
        run: |
          export OPTIMIZE=1
          # Try to install system dependencies for libarchive, but don't fail if unavailable
          sudo apt-get update
          sudo apt-get install -y libarchive-dev || echo "libarchive-dev installation skipped - some archive formats may not be supported"
          # Print Python paths and debug info
          python -c "import sys; print(sys.path)"
          python -c "import libarchive; print(f'libarchive: {libarchive.__file__}')" || echo "libarchive module not available (this is OK)"
          # Build with detailed logging
          pyinstaller --clean --noconfirm --log-level=DEBUG main.spec
        shell: bash

      - name: Build with PyInstaller (macOS)
        if: runner.os == 'macOS'
        run: |
          export OPTIMIZE=1
          # Skip libarchive installation - application works without it
          # Just use Python's built-in zipfile and tarfile modules
          
          # Print Python paths and debug info
          python -c "import sys; print(sys.path)"
          python -c "import zipfile; print(f'zipfile: {zipfile.__file__}')"
          python -c "import tarfile; print(f'tarfile: {tarfile.__file__}')"
          
          # Build with detailed logging (no hidden-import flags when using spec file)
          pyinstaller --clean --noconfirm --log-level=DEBUG main.spec
        shell: bash

      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:OPTIMIZE = 1
          $env:PYTHONPATH = $env:pythonLocation
          $env:PATH = "$env:pythonLocation;$env:pythonLocation\Scripts;$env:PATH"
          
          # Print Python paths and debug info
          python -c "import sys; print(sys.path)"
          python -c "import zipfile; print(f'zipfile: {zipfile.__file__}')"
          python -c "import tarfile; print(f'tarfile: {tarfile.__file__}')"
          python -c "import libarchive; print(f'libarchive: {libarchive.__file__}')" || echo "libarchive module not available (this is OK)"
          
          # Build with PyInstaller with more verbose output (no hidden-import flags when using spec file)
          pyinstaller --clean --noconfirm --log-level=DEBUG main.spec
        shell: pwsh

      # Create platform-specific packages
      - name: Create Linux package
        if: runner.os == 'Linux'
        run: |
          # Test if the executable can run
          dist/userchrome-loader --help || echo "Executable test failed, but continuing..."
          
          # Rename the executable
          mv dist/userchrome-loader dist/userchrome-loader-linux
          
          # Try to copy libarchive shared library if it exists (but don't fail if not)
          if [ -d "/usr/lib/x86_64-linux-gnu" ]; then
            mkdir -p dist/libs
            cp -P /usr/lib/x86_64-linux-gnu/libarchive.so* dist/libs/ || echo "No libarchive libraries found (this is OK)"
          fi
          
          # Create a zip archive for Linux (include libs directory only if it exists and has files)
          cd dist
          if [ -d "libs" ] && [ "$(ls -A libs)" ]; then
            zip -r userchrome-loader-linux.zip userchrome-loader-linux libs
          else
            zip -r userchrome-loader-linux.zip userchrome-loader-linux
          fi
          cd ..

      - name: Create Windows package
        if: runner.os == 'Windows'
        run: |
          # Rename the executable
          mv dist/userchrome-loader.exe dist/userchrome-loader-windows.exe
          # Create a zip archive for Windows
          cd dist && powershell Compress-Archive -Path userchrome-loader-windows.exe -DestinationPath userchrome-loader-windows.zip

      - name: Create macOS package
        if: runner.os == 'macOS'
        run: |
          # First rename the app bundle
          mv dist/userchrome-loader.app dist/userchrome-loader-macos.app
          # Create a zip archive of the app bundle to preserve its structure
          cd dist && zip -r userchrome-loader-macos.zip userchrome-loader-macos.app && cd ..

      - name: Prepare artifacts for upload
        run: |
          mkdir -p userchrome-loader-${{ runner.os }}
          if [ "${{ runner.os }}" == "Linux" ]; then
            cp dist/userchrome-loader-linux.zip userchrome-loader-${{ runner.os }}/
          elif [ "${{ runner.os }}" == "Windows" ]; then
            cp dist/userchrome-loader-windows.zip userchrome-loader-${{ runner.os }}/
          elif [ "${{ runner.os }}" == "macOS" ]; then
            # Copy the zip file
            cp dist/userchrome-loader-macos.zip userchrome-loader-${{ runner.os }}/
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: userchrome-loader-${{ runner.os }}
          path: userchrome-loader-${{ runner.os }}
          retention-days: 90

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts
        run: |
          ls -la artifacts/
          find artifacts -type f | sort



      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/userchrome-loader-Linux/*.zip
            artifacts/userchrome-loader-Windows/*.zip
            artifacts/userchrome-loader-macOS/*.zip
          token: ${{ github.token }}
          draft: false
          prerelease: false
